version: '3.4'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
     - "27017:27017"
    volumes:
     - mongo_data:/data/db
  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
     - "6379:6379"
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
     - "8080:8000"
     - "9000:9000"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    container_name: catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - "Database:ConnectionString=mongodb://mongo:27017"
    depends_on:
     - mongo
    ports:
     - "8080:80"
     #- "8081:443"
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: basket.api
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    environment:
    - "ConnectionStrings:Redis=redis:6379"
    depends_on:
     - redis


volumes:
  mongo_data:
  portainer_data:
